version: 2.1

jobs:
  CI-Phase:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - run:
          name: Install Lerna
          command: sudo npm install -g lerna@3.20.2
      - run:
          name: Lerna Bootstrap
          command: lerna bootstrap
      - run:
          name: Build Client
          command: lerna run build --scope @akshay/ui
          environment:
            CI: "false"
      - run:
          name: Set github user email
          command: git config --global user.email "akshay.r555@gmail.com"
      - run:
          name: Set github user name
          command: git config --global user.name "akshay.harti"
      - run:
          name: Deploy to github pages
          command: lerna run deploy --scope @akshay/ui

workflows:
  version: 2
  master-pipeline:
    jobs:
      - CI-Phase
